sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lewclark174/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lewclark174/docker-react npm run rest

deploy: 
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-347047974149"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
