sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lewclark174/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lewclark174/docker-react npm run rest
